### ISSUE TITLE
Trending: The data Star and Fork from server is wrong

### ISSUE THREAD

**Issue by shenAlexy** [thedillonb/GitHub-Trending#1]
I select Objective-C trending by Today, and I found the data Star and Fork form server is wrong. For instance, my repositories of shenAlexy/MVVM Star and Fork is wrong!

**Comment by thedillonb** [comment]
Are you referring to when you click on your repository? I found yours but it doesn't seem out of sync to me:

![image](https://cloud.githubusercontent.com/assets/1644068/14611510/9dab288c-0560-11e6-99c9-2bb6213bf732.png)

<img width="1060" alt="screen shot 2016-04-18 at 12 24 01 pm" src="https://cloud.githubusercontent.com/assets/1644068/14611516/a4099128-0560-11e6-8514-83e14b1ff691.png">

**Comment by thedillonb** [comment]
The star and fork counters are typically out of sync for a little bit during the day as the application must continuously poll GitHub to retrieve those numbers. The numbers are cached until the next poll cycle occurs and that is why you probably saw out of data information. Unfortunately, the only way to fix that is to decrease the time in between polling - and that causes burden on GitHub's servers as well as increases bandwidth for the server making the calls. I'm not sure if it's worth it.
