### ISSUE TITLE
Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "/GitHub-Trending/public/debug-politics.svg" "-resize" "96x" "/GitHub-Trending/public/debug-politics.png" this most likely means the gm/convert binaries can't be found

### ISSUE THREAD

**Issue by leichunfeng** [thedillonb/GitHub-Trending#5]
GET https://github.com/showcases - {"page":1}
GET https://github.com/showcases - {"page":2}
GET https://github.com/showcases - {"page":3}
GET https://github.com/showcases - {"page":4}
Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "/GitHub-Trending/public/debug-politics.svg" "-resize" "96x" "/GitHub-Trending/public/debug-politics.png" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/GitHub-Trending/node_modules/gm/lib/command.js:299:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by thedillonb** [comment]
You need to install GraphicsMagick. This will differ based on what OS you're using but something like `sudo apt-get install graphicsmagick` would do the trick if you're on linux (and using apt).

**Comment by leichunfeng** [comment]
Thank you very much, I will try it.

**Comment by Abdul-majid-ashrafi** [comment]
@thedillonb @leichunfeng  I am facing this issue in windows can you help me please,
Thanks.

**Comment by thedillonb** [comment]
@Abdul-majid-ashrafi You need to install graphics magick for windows: http://www.graphicsmagick.org/INSTALL-windows.html

**Comment by Abdul-majid-ashrafi** [comment]
@thedillonb Thank you bady

**Comment by Vishnupriya112** [comment]
After installing also am getting error..But If i typed gm in E: its showing installed version
