### ISSUE TITLE
The strategy to perform ./bin/update command

### ISSUE THREAD

**Issue by leichunfeng** [thedillonb/GitHub-Trending#6]
What strategies are used to perform the `./bin/update` command? Should I use the timer to trigger it once a day? Look forward to your reply.

**Comment by thedillonb** [comment]
Holy cow. Some how I missed this. I'm extremely sorry! I have it setup as a cron task that executes once a day. I'll update the trending at 12pm then updating the showcases around 4am. I typically stagger them as I try to prevent a large amount of requests flooding GitHub from a single source.
